[2023-11-26T00:21:24.032+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.load scheduled__2023-11-18T00:00:00+00:00 [queued]>
[2023-11-26T00:21:24.048+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.load scheduled__2023-11-18T00:00:00+00:00 [queued]>
[2023-11-26T00:21:24.049+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-26T00:21:24.069+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load> on 2023-11-18 00:00:00+00:00
[2023-11-26T00:21:24.078+0000] {standard_task_runner.py:57} INFO - Started process 89 to run task
[2023-11-26T00:21:24.111+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'load', 'scheduled__2023-11-18T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpimvubadt']
[2023-11-26T00:21:24.131+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask load
[2023-11-26T00:21:24.319+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.load scheduled__2023-11-18T00:00:00+00:00 [running]> on host decfc1fe5c09
[2023-11-26T00:21:24.497+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-18T00:00:00+00:00'
[2023-11-26T00:21:24.505+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: load_data() missing 1 required positional argument: 'date'
[2023-11-26T00:21:24.560+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=load, execution_date=20231118T000000, start_date=20231126T002124, end_date=20231126T002124
[2023-11-26T00:21:24.585+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task load (load_data() missing 1 required positional argument: 'date'; 89)
[2023-11-26T00:21:24.631+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-26T00:21:24.660+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
